version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "fredriick"

  - package-ecosystem: "npm"
    directory: "/mobile-app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "fredriick"

  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "fredriick"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "fredriick"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "fredriick"
