{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "proxymesh.fullname" . }}-gateway
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "proxymesh.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "proxymesh.fullname" . }}-gateway
                port:
                  number: 80
{{- end }}
