apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxymesh.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "proxymesh.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  redis-password: {{ .Values.redis.password | b64enc | quote }}
