// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/grpc/peer.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Isp           string                 `protobuf:"bytes,5,opt,name=isp,proto3" json:"isp,omitempty"`
	Os            string                 `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`
	Ipv6Subnet    string                 `protobuf:"bytes,7,opt,name=ipv6_subnet,json=ipv6Subnet,proto3" json:"ipv6_subnet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_internal_grpc_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_peer_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ConnectRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ConnectRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ConnectRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ConnectRequest) GetIsp() string {
	if x != nil {
		return x.Isp
	}
	return ""
}

func (x *ConnectRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *ConnectRequest) GetIpv6Subnet() string {
	if x != nil {
		return x.Ipv6Subnet
	}
	return ""
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_internal_grpc_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_peer_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConnectResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type HeartbeatRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Battery           int32                  `protobuf:"varint,2,opt,name=battery,proto3" json:"battery,omitempty"`
	CpuUsage          float32                `protobuf:"fixed32,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	IsCharging        bool                   `protobuf:"varint,4,opt,name=is_charging,json=isCharging,proto3" json:"is_charging,omitempty"`
	BandwidthSent     int64                  `protobuf:"varint,5,opt,name=bandwidth_sent,json=bandwidthSent,proto3" json:"bandwidth_sent,omitempty"`
	BandwidthReceived int64                  `protobuf:"varint,6,opt,name=bandwidth_received,json=bandwidthReceived,proto3" json:"bandwidth_received,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_internal_grpc_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_peer_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetBattery() int32 {
	if x != nil {
		return x.Battery
	}
	return 0
}

func (x *HeartbeatRequest) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HeartbeatRequest) GetIsCharging() bool {
	if x != nil {
		return x.IsCharging
	}
	return false
}

func (x *HeartbeatRequest) GetBandwidthSent() int64 {
	if x != nil {
		return x.BandwidthSent
	}
	return 0
}

func (x *HeartbeatRequest) GetBandwidthReceived() int64 {
	if x != nil {
		return x.BandwidthReceived
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_internal_grpc_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_peer_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BandwidthReport struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	BytesSent       int64                  `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived   int64                  `protobuf:"varint,3,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BandwidthReport) Reset() {
	*x = BandwidthReport{}
	mi := &file_internal_grpc_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BandwidthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BandwidthReport) ProtoMessage() {}

func (x *BandwidthReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BandwidthReport.ProtoReflect.Descriptor instead.
func (*BandwidthReport) Descriptor() ([]byte, []int) {
	return file_internal_grpc_peer_proto_rawDescGZIP(), []int{4}
}

func (x *BandwidthReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *BandwidthReport) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *BandwidthReport) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *BandwidthReport) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type BandwidthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BandwidthResponse) Reset() {
	*x = BandwidthResponse{}
	mi := &file_internal_grpc_peer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BandwidthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BandwidthResponse) ProtoMessage() {}

func (x *BandwidthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_peer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BandwidthResponse.ProtoReflect.Descriptor instead.
func (*BandwidthResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_peer_proto_rawDescGZIP(), []int{5}
}

func (x *BandwidthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BandwidthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_internal_grpc_peer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_peer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_peer_proto_rawDescGZIP(), []int{6}
}

func (x *DisconnectRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DisconnectRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TelemetryStreamRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	BatteryLevel      int32                  `protobuf:"varint,2,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	CpuUsage          float32                `protobuf:"fixed32,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	BandwidthSent     int64                  `protobuf:"varint,4,opt,name=bandwidth_sent,json=bandwidthSent,proto3" json:"bandwidth_sent,omitempty"`
	BandwidthReceived int64                  `protobuf:"varint,5,opt,name=bandwidth_received,json=bandwidthReceived,proto3" json:"bandwidth_received,omitempty"`
	IsCharging        bool                   `protobuf:"varint,6,opt,name=is_charging,json=isCharging,proto3" json:"is_charging,omitempty"`
	IpAddress         string                 `protobuf:"bytes,7,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Timestamp         int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TelemetryStreamRequest) Reset() {
	*x = TelemetryStreamRequest{}
	mi := &file_internal_grpc_peer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryStreamRequest) ProtoMessage() {}

func (x *TelemetryStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_peer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryStreamRequest.ProtoReflect.Descriptor instead.
func (*TelemetryStreamRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_peer_proto_rawDescGZIP(), []int{7}
}

func (x *TelemetryStreamRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TelemetryStreamRequest) GetBatteryLevel() int32 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *TelemetryStreamRequest) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *TelemetryStreamRequest) GetBandwidthSent() int64 {
	if x != nil {
		return x.BandwidthSent
	}
	return 0
}

func (x *TelemetryStreamRequest) GetBandwidthReceived() int64 {
	if x != nil {
		return x.BandwidthReceived
	}
	return 0
}

func (x *TelemetryStreamRequest) GetIsCharging() bool {
	if x != nil {
		return x.IsCharging
	}
	return false
}

func (x *TelemetryStreamRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *TelemetryStreamRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TelemetryStreamResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServerTimestamp   string                 `protobuf:"bytes,1,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	StatusMessage     string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	ConnectionQuality int32                  `protobuf:"varint,3,opt,name=connection_quality,json=connectionQuality,proto3" json:"connection_quality,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TelemetryStreamResponse) Reset() {
	*x = TelemetryStreamResponse{}
	mi := &file_internal_grpc_peer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryStreamResponse) ProtoMessage() {}

func (x *TelemetryStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_peer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryStreamResponse.ProtoReflect.Descriptor instead.
func (*TelemetryStreamResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_peer_proto_rawDescGZIP(), []int{8}
}

func (x *TelemetryStreamResponse) GetServerTimestamp() string {
	if x != nil {
		return x.ServerTimestamp
	}
	return ""
}

func (x *TelemetryStreamResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *TelemetryStreamResponse) GetConnectionQuality() int32 {
	if x != nil {
		return x.ConnectionQuality
	}
	return 0
}

type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_internal_grpc_peer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_peer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_peer_proto_rawDescGZIP(), []int{9}
}

func (x *DisconnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_internal_grpc_peer_proto protoreflect.FileDescriptor

const file_internal_grpc_peer_proto_rawDesc = "" +
	"\n" +
	"\x18internal/grpc/peer.proto\x12\tproxymesh\"\xaa\x01\n" +
	"\x0eConnectRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x10\n" +
	"\x03isp\x18\x05 \x01(\tR\x03isp\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\x12\x1f\n" +
	"\vipv6_subnet\x18\a \x01(\tR\n" +
	"ipv6Subnet\"d\n" +
	"\x0fConnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\xd9\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\abattery\x18\x02 \x01(\x05R\abattery\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x02R\bcpuUsage\x12\x1f\n" +
	"\vis_charging\x18\x04 \x01(\bR\n" +
	"isCharging\x12%\n" +
	"\x0ebandwidth_sent\x18\x05 \x01(\x03R\rbandwidthSent\x12-\n" +
	"\x12bandwidth_received\x18\x06 \x01(\x03R\x11bandwidthReceived\"G\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9b\x01\n" +
	"\x0fBandwidthReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x02 \x01(\x03R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x03 \x01(\x03R\rbytesReceived\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x03R\x0fdurationSeconds\"G\n" +
	"\x11BandwidthResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"D\n" +
	"\x11DisconnectRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xa7\x02\n" +
	"\x16TelemetryStreamRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12#\n" +
	"\rbattery_level\x18\x02 \x01(\x05R\fbatteryLevel\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x02R\bcpuUsage\x12%\n" +
	"\x0ebandwidth_sent\x18\x04 \x01(\x03R\rbandwidthSent\x12-\n" +
	"\x12bandwidth_received\x18\x05 \x01(\x03R\x11bandwidthReceived\x12\x1f\n" +
	"\vis_charging\x18\x06 \x01(\bR\n" +
	"isCharging\x12\x1d\n" +
	"\n" +
	"ip_address\x18\a \x01(\tR\tipAddress\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"\x9a\x01\n" +
	"\x17TelemetryStreamResponse\x12)\n" +
	"\x10server_timestamp\x18\x01 \x01(\tR\x0fserverTimestamp\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\x12-\n" +
	"\x12connection_quality\x18\x03 \x01(\x05R\x11connectionQuality\".\n" +
	"\x12DisconnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x8d\x03\n" +
	"\vPeerService\x12\\\n" +
	"\x0fStreamTelemetry\x12!.proxymesh.TelemetryStreamRequest\x1a\".proxymesh.TelemetryStreamResponse(\x010\x01\x12@\n" +
	"\aConnect\x12\x19.proxymesh.ConnectRequest\x1a\x1a.proxymesh.ConnectResponse\x12F\n" +
	"\tHeartbeat\x12\x1b.proxymesh.HeartbeatRequest\x1a\x1c.proxymesh.HeartbeatResponse\x12K\n" +
	"\x0fReportBandwidth\x12\x1a.proxymesh.BandwidthReport\x1a\x1c.proxymesh.BandwidthResponse\x12I\n" +
	"\n" +
	"Disconnect\x12\x1c.proxymesh.DisconnectRequest\x1a\x1d.proxymesh.DisconnectResponseB\x19Z\x17proxymesh/internal/grpcb\x06proto3"

var (
	file_internal_grpc_peer_proto_rawDescOnce sync.Once
	file_internal_grpc_peer_proto_rawDescData []byte
)

func file_internal_grpc_peer_proto_rawDescGZIP() []byte {
	file_internal_grpc_peer_proto_rawDescOnce.Do(func() {
		file_internal_grpc_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_peer_proto_rawDesc), len(file_internal_grpc_peer_proto_rawDesc)))
	})
	return file_internal_grpc_peer_proto_rawDescData
}

var file_internal_grpc_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_grpc_peer_proto_goTypes = []any{
	(*ConnectRequest)(nil),          // 0: proxymesh.ConnectRequest
	(*ConnectResponse)(nil),         // 1: proxymesh.ConnectResponse
	(*HeartbeatRequest)(nil),        // 2: proxymesh.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 3: proxymesh.HeartbeatResponse
	(*BandwidthReport)(nil),         // 4: proxymesh.BandwidthReport
	(*BandwidthResponse)(nil),       // 5: proxymesh.BandwidthResponse
	(*DisconnectRequest)(nil),       // 6: proxymesh.DisconnectRequest
	(*TelemetryStreamRequest)(nil),  // 7: proxymesh.TelemetryStreamRequest
	(*TelemetryStreamResponse)(nil), // 8: proxymesh.TelemetryStreamResponse
	(*DisconnectResponse)(nil),      // 9: proxymesh.DisconnectResponse
}
var file_internal_grpc_peer_proto_depIdxs = []int32{
	7, // 0: proxymesh.PeerService.StreamTelemetry:input_type -> proxymesh.TelemetryStreamRequest
	0, // 1: proxymesh.PeerService.Connect:input_type -> proxymesh.ConnectRequest
	2, // 2: proxymesh.PeerService.Heartbeat:input_type -> proxymesh.HeartbeatRequest
	4, // 3: proxymesh.PeerService.ReportBandwidth:input_type -> proxymesh.BandwidthReport
	6, // 4: proxymesh.PeerService.Disconnect:input_type -> proxymesh.DisconnectRequest
	8, // 5: proxymesh.PeerService.StreamTelemetry:output_type -> proxymesh.TelemetryStreamResponse
	1, // 6: proxymesh.PeerService.Connect:output_type -> proxymesh.ConnectResponse
	3, // 7: proxymesh.PeerService.Heartbeat:output_type -> proxymesh.HeartbeatResponse
	5, // 8: proxymesh.PeerService.ReportBandwidth:output_type -> proxymesh.BandwidthResponse
	9, // 9: proxymesh.PeerService.Disconnect:output_type -> proxymesh.DisconnectResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_peer_proto_init() }
func file_internal_grpc_peer_proto_init() {
	if File_internal_grpc_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_peer_proto_rawDesc), len(file_internal_grpc_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_peer_proto_goTypes,
		DependencyIndexes: file_internal_grpc_peer_proto_depIdxs,
		MessageInfos:      file_internal_grpc_peer_proto_msgTypes,
	}.Build()
	File_internal_grpc_peer_proto = out.File
	file_internal_grpc_peer_proto_goTypes = nil
	file_internal_grpc_peer_proto_depIdxs = nil
}
